language: python
python:
  - "3.6"
install:
  - pip install --quiet .
script:
  - python download.py
  - pytest
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    branch: master