language: python
python:
  - "3.6"
install:
  - pip install --quiet .
script:
  - pytest --flake8
  - codecov --token=$CODECOV_TOKEN
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    branch: master